-- dgomez@vortexbird.com
-- 11/20/2020

INSERT INTO TRANSACTION_TYPE(NAME, ENABLE)VALUES ('WITHDRAW', 'Y');
INSERT INTO TRANSACTION_TYPE(NAME, ENABLE)VALUES ('DEPOSIT', 'Y');
INSERT INTO TRANSACTION_TYPE(NAME, ENABLE)VALUES ('TRANSFER', 'Y');
